common: &default_settings
  MERCADO_PAGO_PUBLIC_KEY: TEST-111222333
  MERCADO_PAGO_ACCESS_TOKEN: TEST-111222333

development:
  <<: *default_settings

staging:
  <<: *default_settings

production:
  <<: *default_settings
